config/routes.rb
Pelucashop::Application.routes.draw do
  resources :cart_items

  resources :carts

  devise_for :users

  resources :wigs

  root :to => "wigs#index"

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :cart_items, :dependent => :destroy

  def total_price
    # cart_items.to_a.sum{|cart_item| cart_item.total_price}
    CartItem.joins(:wig).where(:cart_id => self.id).sum("quantity * price")
  end

  def add_cart_item(wig)
    current_cart_item = self.cart_items.where(:wig_id => wig.id).first
    if current_cart_item
      current_cart_item.quantity += 1
    else
      current_cart_item = CartItem.new(:wig_id => wig.id)
      cart_items << current_cart_item
    end
    current_cart_item
  end
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :wig

  def total_price
    quantity * wig.price
  end

  def as_json(options={})
    super(options.merge(:methods => :total_price, :only => [:id, :quantity], :include => {:wig => {:only => :price}}))
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/wig.rb
class Wig < ActiveRecord::Base
  SIZE = ['Large', 'Medium', 'Small']
  COLOR = ['Negra', 'Naranja', 'Roja', 'Rubia', 'Azul']
  
  validates_inclusion_of    :color, :in => COLOR, :message => 'no es valido'
  validates_inclusion_of    :size,  :in => SIZE, :message => 'no es valido'
  validates_numericality_of :price, :message => 'no es un numero'

  mount_uploader :picture, PictureUploader

  has_many :cart_items

  #before_destroy :verify_cart_items_existence
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :current_cart

  private

  def current_cart
    @cart = Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    @cart = Cart.create
    session[:cart_id] = @cart.id
    @cart
  end

end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  # GET /cart_items
  # GET /cart_items.json
  def index
    @cart_items = CartItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cart_items }
    end
  end

  # GET /cart_items/1
  # GET /cart_items/1.json
  def show
    @cart_item = CartItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cart_item }
    end
  end

  # GET /cart_items/new
  # GET /cart_items/new.json
  def new
    @cart_item = CartItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart_item }
    end
  end

  # GET /cart_items/1/edit
  def edit
    @cart_item = CartItem.find(params[:id])
  end

  # POST /cart_items?wig_id={1}
  # POST /cart_items.json
  def create
    @cart = current_cart
    wig = Wig.find(params[:wig_id])
    @cart_item = @cart.add_cart_item(wig)

    respond_to do |format|
      if @cart_item.save
        format.html { redirect_to root_path, notice: 'Cart item was successfully created.' }
        format.json { render json: @cart_item.as_json, status: :created, location: @cart_item }
      else
        format.html { render action: "new" }
        format.json { render json: @cart_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cart_items/1
  # PUT /cart_items/1.json
  def update
    @cart_item = CartItem.find(params[:id])

    respond_to do |format|
      if @cart_item.update_attributes(params[:cart_item])
        format.html { redirect_to @cart_item, notice: 'Cart item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cart_items/1
  # DELETE /cart_items/1.json
  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy

    respond_to do |format|
      format.html { redirect_to cart_items_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = Cart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end
end

app/controllers/wigs_controller.rb
class WigsController < ApplicationController

  before_filter :authenticate_user!, :except => [:index, :show]

  # GET /wigs
  # GET /wigs.json
  def index
    @wigs = Wig.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @wigs }
    end
  end

  # GET /wigs/1
  # GET /wigs/1.json
  def show
    @wig = Wig.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @wig }
    end
  end

  # GET /wigs/new
  # GET /wigs/new.json
  def new
    @wig = Wig.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @wig }
    end
  end

  # GET /wigs/1/edit
  def edit
    @wig = Wig.find(params[:id])
  end

  # POST /wigs
  # POST /wigs.json
  def create
    @wig = Wig.new(params[:wig])

    respond_to do |format|
      if @wig.save
        format.html { redirect_to @wig, notice: 'Wig was successfully created.' }
        format.json { render json: @wig, status: :created, location: @wig }
      else
        format.html { render action: "new" }
        format.json { render json: @wig.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /wigs/1
  # PUT /wigs/1.json
  def update
    @wig = Wig.find(params[:id])

    respond_to do |format|
      if @wig.update_attributes(params[:wig])
        format.html { redirect_to @wig, notice: 'Wig was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @wig.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wigs/1
  # DELETE /wigs/1.json
  def destroy
    @wig = Wig.find(params[:id])
    @wig.destroy

    respond_to do |format|
      format.html { redirect_to wigs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/wigs_helper.rb
module WigsHelper
end

app/views/cart_items/_cart_item.html.erb
<tr>
  <td><span id="quantity_item_<%= cart_item.id%>"><%= cart_item.quantity %></span> Peluca(s) <%= cart_item.wig.color %> <%= cart_item.wig.size %></td>
  <td><span id="total_item_<%= cart_item.id %>"><%= cart_item.total_price %></span></td>
</tr>

app/views/cart_items/_form.html.erb
<%= form_for(@cart_item) do |f| %>
  <% if @cart_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart_item.errors.count, "error") %> prohibited this cart_item from being saved:</h2>

      <ul>
      <% @cart_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cart_items/edit.html.erb
<h1>Editing cart_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart_item %> |
<%= link_to 'Back', cart_items_path %>

app/views/cart_items/index.html.erb
<h1>Listing cart_items</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cart_items.each do |cart_item| %>
  <tr>
    <td><%= link_to 'Show', cart_item %></td>
    <td><%= link_to 'Edit', edit_cart_item_path(cart_item) %></td>
    <td><%= link_to 'Destroy', cart_item, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart item', new_cart_item_path %>

app/views/cart_items/new.html.erb
<h1>New cart_item</h1>

<%= render 'form' %>

<%= link_to 'Back', cart_items_path %>

app/views/cart_items/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_cart_item_path(@cart_item) %> |
<%= link_to 'Back', cart_items_path %>

app/views/carts/_cart.html.erb
<table>
  <tr>
    <th>Descripción</th>
    <th>Total</th>
  </tr>
    <%= render :partial => "cart_items/cart_item", :collection => cart.cart_items %>
  <tr>
    <td>Total a pagar</td>
    <td><span id="total_a_pagar"><%= cart.total_price %></span></td>
  </tr>
</table>

<%= link_to 'Regresar a catálogo', root_path %> | 
<%= button_to "Vaciar carrito", cart, :method => :delete, :confirm => 'are you sure?'%>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<table>
  <tr>
    <th>Descripción</th>
    <th>Total</th>
  </tr>
  <% @cart.cart_items.each do |cart_item| %>
    <tr>
      <td><%= cart_item.quantity %> Peluca(s) <%= cart_item.wig.color %> <%= cart_item.wig.size %></td>
      <td><%= cart_item.total_price %></td>
    </tr>
  <% end %>
  <tr>
    <td>Total a pagar</td>
    <td><%= @cart.total_price %></td>
  </tr>
</table>

<%= link_to 'Regresar a catálogo', root_path %> | 
<%= button_to "Vaciar carrito", @cart, :method => :delete, :confirm => 'are you sure?'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pelucashop</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <% if current_user %>
    Hola <%= current_user.email %>, <%= link_to "Salir", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign in", new_user_session_path %>
  <% end %>
  <div id ="cart">
    <%= render :partial => "carts/cart", :locals => {:cart => @cart} %>
  </div>
  <%= yield %>

</body>
</html>

app/views/wigs/_form.html.erb
<%= form_for(@wig) do |f| %>
  <% if @wig.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@wig.errors.count, "error prohibio", 'errores prohibieron') %> tu peluca:</h2>

      <ul>
      <% @wig.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :color %> *<br />
    <%= f.select :color, Wig::COLOR, :include_blank => true%>
  </div>
  <div class="field">
    <%= f.label :size, 'Tamaño' %> *<br />
    <%= f.select :size,  Wig::SIZE, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :style, 'Estilo' %><br />
    <%= f.text_field :style %>
  </div>
  <div class="field">
    <%= f.label :price, 'Precio' %> * <br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :picture, 'Foto' %> * <br />
    <%= f.file_field :picture %>
  </div>

  <div class="actions">
    <%= f.submit 'Crear Peluca' %>
  </div>
  
<% end %>

app/views/wigs/edit.html.erb
<h1>Editing wig</h1>

<%= render 'form' %>

<%= link_to 'Show', @wig %> |
<%= link_to 'Back', wigs_path %>

app/views/wigs/index.html.erb
<h1>Listing wigs</h1>

<table>
  <tr>
    <th>Color</th>
    <th>Size</th>
    <th>Style</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @wigs.each do |wig| %>
  <tr>
    <td><%= wig.color %></td>
    <td><%= wig.size %></td>
    <td><%= wig.style %></td>
    <td><%= wig.price %></td>
    <td><%= link_to 'Show', wig %></td>
    <td><%= link_to 'Edit', edit_wig_path(wig) %></td>
    <td><%= link_to 'Destroy', wig, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Wig', new_wig_path %>

app/views/wigs/new.html.erb
<h1>Nueva Peluca</h1>

<%= render 'form' %>

<%= link_to 'Back', wigs_path %>

app/views/wigs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Color:</b>
  <%= @wig.color %>
</p>

<p>
  <b>Size:</b>
  <%= @wig.size %>
</p>

<p>
  <b>Style:</b>
  <%= @wig.style %>
</p>

<p>
  <b>Price:</b>
  <%= @wig.price %>
</p>

<p>
  <b>Foto:</b>
  <%= image_tag @wig.picture.url %>
</p>

<%= button_to "Añadir a carrito", cart_items_path(:wig_id => @wig.id), :id => "add_to_cart", :data_wig => @wig.id  %>

<%= link_to 'Edit', edit_wig_path(@wig) %> |
<%= link_to 'Back', wigs_path %>